import localFont from "next/font/local";
import "../styles/globals.scss";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
    <header>
      <nav>
        <ul>
          <li><a href="/">Home</a></li>
          <li><a href="/about">About</a></li>
          <li><a href="/services">Services</a></li>
          <li><a href="/solutions">Solutions</a></li>
          <li><a href="/contact">Contact</a></li>
          <li><a href="/terms">Terms</a></li>
          <li><a href="/cookies">Cookies</a></li>
        </ul>
      </nav>
    </header>
    {children}
    <footer>
      <p>&copy; {new Date().getFullYear()} Lexi. All Rights Reserved.</p>
      <p className="footer-engineered">
        <a href="https://nuclecode.uk" target="_blank" rel="noopener noreferrer">
        Engineered by nuclecode
      </a></p>
    </footer>
    </body>
    </html>
  );
}
